blank_issues_enabled: false
contact_links:
  - name: Question or support
    url: https://github.com/manulzweb/riwi-cine-backend-1/discussions
    description: Ask questions about setup or usage of the API. Please do not open issues for support questions.
